version: 0.2

env:
  variables:
    IMAGE_BASE_NAME: 'swisstopo/service-qr-code'
    SHELL: /bin/bash
    AWS_DEFAULT_REGION: eu-central-1
    ORGNAME: "swisstopo"
    USER: "aws_code_build"
  parameter-store:
    CI_DOCKERHUB_USER: "/dockerhub/user"
    CI_DOCKERHUB_PASSWORD: "/dockerhub/password"

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "Installing necessary softwares"
      - docker login -u ${CI_DOCKERHUB_USER} -p ${CI_DOCKERHUB_PASSWORD}
      - apt-get update && apt-get install -y docker-compose
  pre_build:
    commands:
      - echo "Initializing submodules"
      - git submodule update --init --recursive
      - echo "export of the image tag for build and push purposes"
      - export IMAGE_TAG=$(git rev-parse --short HEAD)
      - echo "creating a clean environment"
      - make clean setup
  build:
    commands:
      - make build
  post_build:
    commands:
      - make test
      - make push