version: "2"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: --config otel-local-config.yaml
    volumes:
      - ./otel-local-config.yaml:/otel-local-config.yaml
    ports:
      - "4317:4317"

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
