openapi: "3.0.0"
info:
  version: "1.0.0"
  title: Service QRCode

paths:
  /v4/qrcode/checker:
    get:
      summary: Route to check if the service is up.
      operationId: checker
      tags:
        - checker
      responses:
        "200":
          description: Returning OK
          content:
            text/html:
              schema:
                type: string
                example: "OK"
        "500":
          description: Internal Error
          content:
            text/html:
              schema:
                type: string
                example: "The server encountered an internal error"

  /v4/qrcode/generate:
    post:
      summary: Generate a QR code describing the shortened given URL.
      operationId: generateQrCode
      tags:
        - generation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - url
              properties:
                url:
                  type: string
                  description: The url for which a QR code needs to be generated
            example: { url: "https://example.admin.ch" }
      responses:
        "200":
          description: Returning a QR Code describing the link.
          content:
            image/png:
              schema:
                type: object
        "400":
          description: Bad Requests from the client. This can be caused by the absence of the url parameter, the host can't be determined from the request or the host/the domain is/are not part of the authorised hosts / domains.
          content:
            text/html:
              schema:
                type: string
                example: "The property 'url' is missing from the request body"

        "500":
          description: unexpected error
          content:
            text/html:
              schema:
                type: string
                example: "An internal error occured during the QR Code generation"
