name: PR Auto Labeler

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pr-labeler:
    uses: geoadmin/.github/.github/workflows/pr-labeler.yml@master
